const express = require("express")
const { registername, loginuser, logout, frogotpassword, resetpassword, updateprofile, getalluser, getsingleuser } = require("../controllers/usercontroller")
const { isauthenticateduser, authorizeroles } = require("../middelware/auth")
const router =express.Router()
router.route("/register").post(registername)
router.route("/login").post(loginuser)
router.route("/logout").get(logout)
router.route("/password/forgot").post(frogotpassword)
router.route("/password/reset/:token").put(resetpassword)
router.route("/me/update").put(isauthenticateduser,updateprofile)
router.route("/admin/users").get(isauthenticateduser,authorizeroles("admin"),getalluser)
router.route("/admin/users/:id").get(isauthenticateduser,authorizeroles("admin"),getsingleuser)
module.exports =router